image: python:3.8
stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:
  stage: deploy
  environment: production
  only:
    - main
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - echo "Deploying application..."
    - aws s3 sync dist/ s3://www.betasource.tech --delete
    - aws cloudfront create-invalidation --distribution-id E1RZYSISKHQQ71 --paths "/*"
    - echo "Application successfully deployed..."
