image: node:16-alpine

stages:
  - build
  - deploy

build-job:
  stage: build
  only:
    - main
  script:
    - npm install uglifyjs cssnano
    # Minify JavaScript files
    - uglifyjs -o output/main.min.js assets/js/main.js
    - uglifyjs -o output/counterup.min.js assets/js/counterup.min.js
    - uglifyjs -o output/jquery-3.4.1.min.js assets/js/jquery-3.4.1.min.js
    - uglifyjs -o output/bootstrap.min.js assets/js/bootstrap.min.js
    # Minify CSS files
    - npx cssnano -b assets/css/all.min.css output/all.min.css
    - npx cssnano -b assets/css/animate.css output/animate.min.css
    - npx cssnano -b assets/css/bootstrap.min.css output/bootstrap.min.css
    - npx cssnano -b assets/css/style.css output/style.min.css
    - cp -r output/* .

deploy-job:
  stage: deploy
  environment: production
  only:
    - main
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - echo "Deploying application..."
    - aws s3 sync . s3://www.betasource.tech
    - aws s3 sync . s3://betasource.tech
    - aws cloudfront create-invalidation --distribution-id E1RZYSISKHQQ71 --paths "/*"
    - echo "Application successfully deployed..."

